### ISSUE TITLE
Destinations schema

### ISSUE THREAD

**Issue by hbjydev** [hbjydev/bacman#5]
Thinking something like

```yaml
destinations:
  - name: destination_name
    s3Destination:
      endpoint: ''
      region: ''
      storageClass: ''
      bucket: ''
      prefix: ''  # maybe allow templating so you can datetime your uploads
      credentials: <something for storing or referencing secrets>
```
